import { TEMPORAL_DURATION_CLONE_HANDLER } from "./duration";
import { TEMPORAL_INSTANT_CLONE_HANDLER } from "./instant";
import { TEMPORAL_PLAIN_DATE_CLONE_HANDLER } from "./plainDate";
import { TEMPORAL_PLAIN_DATE_TIME_CLONE_HANDLER } from "./plainDateTime";
import { TEMPORAL_PLAIN_MONTH_DAY_CLONE_HANDLER } from "./plainMonthDay";
import { TEMPORAL_PLAIN_TIME_CLONE_HANDLER } from "./plainTime";
import { TEMPORAL_PLAIN_YEAR_MONTH_CLONE_HANDLER } from "./plainYearMonth";
import { TEMPORAL_ZONED_DATE_TIME_CLONE_HANDLER } from "./zonedDateTime";

export const TEMPORAL_HANDLERS = [
	TEMPORAL_DURATION_CLONE_HANDLER,
	TEMPORAL_INSTANT_CLONE_HANDLER,
	TEMPORAL_PLAIN_DATE_CLONE_HANDLER,
	TEMPORAL_PLAIN_DATE_TIME_CLONE_HANDLER,
	TEMPORAL_PLAIN_MONTH_DAY_CLONE_HANDLER,
	TEMPORAL_PLAIN_TIME_CLONE_HANDLER,
	TEMPORAL_PLAIN_YEAR_MONTH_CLONE_HANDLER,
	TEMPORAL_ZONED_DATE_TIME_CLONE_HANDLER,
];
